# Production Docker Compose - Single container on port 80
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hubpkt-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_API_KEY: ${VITE_API_KEY}
        VITE_JOTFORM_API_KEY: ${VITE_JOTFORM_API_KEY}
        VITE_JOTFORM_FORM_ID: ${VITE_JOTFORM_FORM_ID}
        VITE_JOTFORM_FORM_CREATORS_ID: ${VITE_JOTFORM_FORM_CREATORS_ID}
        VITE_TRACKING_ID_GA: ${VITE_TRACKING_ID_GA}
        VITE_ENV_TYPE: ${VITE_ENV_TYPE}
        NODE_ENV: production
    container_name: hubpkt-app
    ports:
      - "3000:80"
      - "4001:4001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - API_KEY=${API_KEY}
      - CLIENT_ORIGIN=${CLIENT_ORIGIN}
      - VITE_API_KEY=${VITE_API_KEY}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_JOTFORM_API_KEY=${VITE_JOTFORM_API_KEY}
      - VITE_JOTFORM_FORM_ID=${VITE_JOTFORM_FORM_ID}
      - VITE_JOTFORM_FORM_CREATORS_ID=${VITE_JOTFORM_FORM_CREATORS_ID}
      - VITE_TRACKING_ID_GA=${VITE_TRACKING_ID_GA}
      - STORAGE_BASE_PATH=${STORAGE_BASE_PATH}
      - NGINX_BASE_URL=${NGINX_BASE_URL}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - ALLOWED_FILE_TYPES=${ALLOWED_FILE_TYPES}
      - REGISTRATION_CODE=${REGISTRATION_CODE}
      - NODE_ENV=production
      - PORT=4001
    volumes:
      - uploads-data:/app/uploads
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
  uploads-data:  # New volume for persistent file storage