# Production Docker Compose - Single container on port 80
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_API_KEY: ${VITE_API_KEY}
        VITE_JOTFORM_API_KEY: ${VITE_JOTFORM_API_KEY}
        VITE_JOTFORM_FORM_ID: ${VITE_JOTFORM_FORM_ID}
        VITE_JOTFORM_FORM_CREATORS_ID: ${VITE_JOTFORM_FORM_CREATORS_ID}
        VITE_TRACKING_ID_GA: ${VITE_TRACKING_ID_GA}
        VITE_ENV_TYPE: ${VITE_ENV_TYPE}
        NODE_ENV: production
    container_name: hubpkt-app
    ports:
      - "127.0.0.1:3000:80"
      - "127.0.0.1:4001:4001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - API_KEY=${API_KEY}
      - CLIENT_ORIGIN=${CLIENT_ORIGIN}
      - VITE_API_KEY=${VITE_API_KEY}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_JOTFORM_API_KEY=${VITE_JOTFORM_API_KEY}
      - VITE_JOTFORM_FORM_ID=${VITE_JOTFORM_FORM_ID}
      - VITE_JOTFORM_FORM_CREATORS_ID=${VITE_JOTFORM_FORM_CREATORS_ID}
      - VITE_TRACKING_ID_GA=${VITE_TRACKING_ID_GA}
      - STORAGE_BASE_PATH=${STORAGE_BASE_PATH}
      - NGINX_BASE_URL=${NGINX_BASE_URL}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - ALLOWED_FILE_TYPES=${ALLOWED_FILE_TYPES}
      - REGISTRATION_CODE=${REGISTRATION_CODE}
      - NODE_ENV=production
      - PORT=4001
    volumes:
      - /home/hub/hub_data:/app/uploads
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
    